import type { Project } from '@/lib/types';

export type DemoProject = Project & { demo: true; demo_art: 'art-1' | 'art-2' | 'art-3' };

export const demoProjects: DemoProject[] = [
  { id:'demo-1', title:'Dia das Mães', slug:'dia-das-maes', category:'Campanha / Motion', format:'9:16', media_mode:'video', year:2026, client:'Elgin', role:'Direção de arte', intro:'Uma campanha pensada para aproximar produto, afeto e rotina.', challenge:'Criar uma presença digital de Dia das Mães que apresentasse produto sem perder o lado humano da marca.', direction:'Direção de arte, linguagem visual, cenas e movimento construídos para manter unidade entre filme e digital.', result:'Uma campanha visualmente consistente, preparada para vídeo, social e e-commerce.', cover_url:'', gallery_urls:[], video_url:null, credits:null, featured:true, published:true, sort_order:1, created_at:'', updated_at:'', demo:true, demo_art:'art-1' },
  { id:'demo-2', title:'Uma marca com presença.', slug:'uma-marca-com-presenca', category:'Branding / Social', format:'3:4', media_mode:'carousel', year:2026, client:null, role:'Direção de arte', intro:'Identidade e conteúdo desenhados para ocupar o feed com clareza.', challenge:'Construir uma linguagem que funcionasse com consistência em peças sociais e pontos de contato digitais.', direction:'Sistema visual modular, tipografia forte e composição pensada para diferentes formatos.', result:'Uma presença digital reconhecível, adaptável e pronta para escala.', cover_url:'', gallery_urls:['demo-01','demo-02','demo-03'], video_url:null, credits:null, featured:true, published:true, sort_order:2, created_at:'', updated_at:'', demo:true, demo_art:'art-2' },
  { id:'demo-3', title:'Imagem em movimento.', slug:'imagem-em-movimento', category:'Filme / Direção', format:'16:9', media_mode:'video', year:2026, client:null, role:'Direção', intro:'Imagem, ritmo e direção trabalhando como uma única linguagem.', challenge:'Criar um filme com personalidade visual, ritmo e espaço para a ideia respirar.', direction:'Direção visual, composição e movimento com foco em narrativa e impacto.', result:'Um filme que funciona como peça principal e também gera desdobramentos para digital.', cover_url:'', gallery_urls:[], video_url:null, credits:null, featured:true, published:true, sort_order:3, created_at:'', updated_at:'', demo:true, demo_art:'art-3' },
  { id:'demo-4', title:'Identidade que sustenta a marca.', slug:'identidade-que-sustenta-a-marca', category:'Branding / Identidade', format:'1:1', media_mode:'single', year:2026, client:null, role:'Direção de arte', intro:'Uma identidade desenhada para dar consistência à marca.', challenge:'Criar um sistema visual simples, reconhecível e adaptável.', direction:'Identidade visual, composição e aplicações pensadas para diferentes pontos de contato.', result:'Uma base visual clara para manter a marca consistente.', cover_url:'', gallery_urls:[], video_url:null, credits:null, featured:false, published:true, sort_order:4, created_at:'', updated_at:'', demo:true, demo_art:'art-2' },
  { id:'demo-5', title:'Um feed com direção.', slug:'um-feed-com-direcao', category:'Social / Carrossel', format:'3:4', media_mode:'carousel', year:2026, client:null, role:'Direção de arte', intro:'Um sistema de conteúdo que transforma informação em linguagem visual.', challenge:'Criar um carrossel que mantivesse unidade entre páginas e leitura rápida.', direction:'Grid, tipografia e ritmo visual construídos para o formato 1080×1440.', result:'Um carrossel pensado para leitura, retenção e identidade.', cover_url:'', gallery_urls:['demo-01','demo-02','demo-03'], video_url:null, credits:null, featured:false, published:true, sort_order:5, created_at:'', updated_at:'', demo:true, demo_art:'art-2' },
  { id:'demo-6', title:'Do impresso ao digital.', slug:'do-impresso-ao-digital', category:'Editorial / Impresso', format:'16:9', media_mode:'gallery', year:2026, client:null, role:'Direção de arte', intro:'Projetos editoriais que atravessam o papel e chegam ao digital.', challenge:'Organizar conteúdo editorial com hierarquia visual e consistência de marca.', direction:'Diagramação, direção visual, tratamento de imagem e adaptações para digital.', result:'Uma linguagem editorial preparada para jornal, revista, panfleto e peças digitais.', cover_url:'', gallery_urls:[], video_url:null, credits:null, featured:false, published:true, sort_order:6, created_at:'', updated_at:'', demo:true, demo_art:'art-3' },
];
